public class ClassToBeTested {
    public static Integer addNumbers(Integer a, Integer b) {
        Integer sum = a + b;
        return sum;
        //comment 1 in dev1
    }
    
     public static Integer substractNumbers(Integer a, Integer b) {
        Integer substract = a - b;
        return substract;
    }
    
     public static Integer multiplyNumbers(Integer a, Integer b) {
        Integer multiply = a * b;
        return multiply;
    }
}